"""add organization usage logs

Revision ID: 82b3d11ccf5d
Revises: f5099cea1774
Create Date: 2026-05-09 23:42:50.003928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '82b3d11ccf5d'
down_revision: Union[str, Sequence[str], None] = 'f5099cea1774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'last_verification_email_sent_at')
    op.drop_column('users', 'activation_token_expires')
    op.drop_column('users', 'credits_balance')
    op.drop_column('users', 'last_reset_email_sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_reset_email_sent_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('credits_balance', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('users', sa.Column('activation_token_expires', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('last_verification_email_sent_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), nullable=True))
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('job_type', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('input', sqlite.JSON(), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('progress', sa.INTEGER(), nullable=False),
    sa.Column('status_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    # ### end Alembic commands ###
