"""add api keys table

Revision ID: 3508b7dc21e7
Revises: be584db57ebb
Create Date: 2026-05-24 11:21:27.083773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3508b7dc21e7'
down_revision: Union[str, Sequence[str], None] = 'be584db57ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.alter_column('business_analyses', 'has_charts',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('business_analyses', 'has_forecast',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('business_analyses', 'has_ai_narrative',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_analyses', 'has_ai_narrative',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('business_analyses', 'has_forecast',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('business_analyses', 'has_charts',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
