"""add api access fields to users

Revision ID: a0e66e2aa655
Revises: d123f13252b5
Create Date: 2026-05-24 12:57:45.357702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0e66e2aa655"
down_revision: Union[str, Sequence[str], None] = "d123f13252b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds API access fields to users.

    The business_analyses Boolean ALTER COLUMN operations generated by Alembic
    were intentionally removed because SQLite does not support ALTER COLUMN
    in that form.
    """
    op.add_column(
        "users",
        sa.Column(
            "api_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "api_plan",
            sa.String(),
            nullable=True,
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "api_credits_balance",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("users", "api_credits_balance")
    op.drop_column("users", "api_plan")
    op.drop_column("users", "api_enabled")
