"""fix business analysis boolean flags

Revision ID: be584db57ebb
Revises: 037d3240d8f3
Create Date: 2026-05-21 18:23:11.062230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be584db57ebb'
down_revision: Union[str, Sequence[str], None] = '037d3240d8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_analyses', 'has_charts',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('business_analyses', 'has_forecast',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('business_analyses', 'has_ai_narrative',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_analyses', 'has_ai_narrative',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('business_analyses', 'has_forecast',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('business_analyses', 'has_charts',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
