"""add api usage table

Revision ID: d123f13252b5
Revises: 3508b7dc21e7
Create Date: 2026-05-24 11:58:47.869201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d123f13252b5"
down_revision: Union[str, Sequence[str], None] = "3508b7dc21e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    This migration intentionally creates only the api_usage table.
    The business_analyses boolean column changes generated by Alembic
    were removed because SQLite does not support ALTER COLUMN in that form.
    """
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("agent", sa.String(), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_api_usage_id"),
        "api_usage",
        ["id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_api_usage_id"),
        table_name="api_usage",
    )

    op.drop_table("api_usage")
